### PR TITLE
Add support for sharing references between structures

### PR DESCRIPTION
**Pull request by gdeest**
My modest proposal for ticket to allow rmultiple graphs to share the same nodes through a traversable instance.

Please don't merge yet.

### CODE REVIEW

**Comment by gdeest** [comment]
OK, I need to make this compile on older GHC versions and I just spotted an obvious bug, but the intent should already be pretty clear.

Let me know if you have any feedback.

**Comment by gdeest** [comment]
Waiting for review !

**Comment by RyanGlScott** [comment]
@gdeest, is it expected that this patch should change the user-visible behavior of `reifyGraph`? I ask since `data-reify-0.6.2` (which is the first `data-reify` release to feature your patch) causes the `ad` test suite to fail: ekmett/ad#89. Any insight you could provide here would be very much appreciated.

**Comment by RyanGlScott** [comment]
I've moved https://github.com/ku-fpg/data-reify/pull/8#issuecomment-702442549 to its own issue in #11, where I have identified a small example whose behavior changes between 0.6.1 and 0.6.2.

**Comment by gdeest** [comment]
Hmmm, This was a long time ago, but no, I don't think this is expected — I'll have a look this weekend to see if I figure it out.

**Pull request merged**
